### PR TITLE
Ensure that escope is parsing decorators.

### PR DESCRIPTION
**Pull request by matteosuppo**
Address issue https://github.com/babel/babel-eslint/issues/72

### CODE REVIEW

**Comment by slonoed** [comment]
@matteosuppo what with this PR?

**Comment by matteosuppo** [comment]
It's a step toward fixing issue 72

Il giorno ven 1 mag 2015 18:45 Dmitry Manannikov <notifications@github.com>
ha scritto:

**Comment by MoOx** [comment]
@matteosuppo do you need any hand to update this PR ?
I would love to see this one ready to merge :)

**Comment by matteosuppo** [comment]
I'm not even sure if they want to merge it

Il giorno gio 14 mag 2015 14:03 Maxime Thirouin <notifications@github.com>
ha scritto:

**Comment by MoOx** [comment]
Who doesn't want to merge a PR that fix an issue ?
Maybe you can add tests ? Not sure if it's necessary here but that might help.

**Comment by sebmck** [comment]
I haven't merged this because I'm not comfortable with the code as I'm not even show what this does. Also #88.

**Comment by MoOx** [comment]
That why I think tests might help here :)
I saw this issue as well, I am sure you are very busy. I don't want to annoy you :)

**Comment by hzoo** [comment]
Thanks for the initial PR @matteosuppo!

**Pull request closed without merging**
