### PR TITLE
use node.babelType for SpreadProperty

### PR DESCRIPTION
**Pull request by hzoo**
Is this good?

@sebmck @jquense

### CODE REVIEW

**Comment by sebmck** [comment]
I meant more putting `node._babelType = node.type;` at the top of the `enter` visitor so all nodes have their original pure type.

**Comment by hzoo** [comment]
Ah ok that makes more sense

**Comment by hzoo** [comment]
this what you meant?

**Comment by sebmck** [comment]
:+1:

**Pull request merged**
