### PR TITLE
Revert bump to babel 51

### PR DESCRIPTION
**Pull request by existentialism**

### CODE REVIEW

**Comment by hzoo** [comment]
Forgot that in beta we dropped Node 4, so having a non-beta version drop it automatically was unintentional. Yeah we'll revert here with a patch and do a new version.

I guess `9.0.0-beta.0`? We could also switch to using a peerDep on `@babel/core` instead

**Comment by TrySound** [comment]
We can't consume new syntax features. Would be good if you will release beta.

**Comment by existentialism** [comment]
@TrySound published v9.0.0-beta.1!

**Comment by TrySound** [comment]
Awesome! Thank you

**Pull request merged**
