### PR TITLE
Use babylon estree and ranges

### LINKED ISSUE #440: Use Babylon ESTree plugin
to remove a lot of the ast hacks that are already done via the plugin.

https://github.com/babel/babylon#output

basically everything in https://github.com/babel/babel-eslint/blob/master/babylon-to-espree/toAST.js

This will make this project a lot simpler and my soul ☺️

### PR DESCRIPTION
**Pull request by danez**
Fixes #440

### CODE REVIEW

**Comment by hzoo** [comment]
we might be able to remove some other stuff in babylon-to-estree

**Comment by danez** [comment]
Wasn't sure, a lot of other stuff is unrelated to estree, tokens, types. But yeah maybe there is some more.

**Comment by hzoo** [comment]
maybe 

like https://github.com/babel/babel-eslint/blob/master/babylon-to-espree/index.js#L32-L33
https://github.com/babel/babel-eslint/blob/master/babylon-to-espree/convertComments.js#L14

**Comment by hzoo** [comment]
can land when it passes, can iterate

**Comment by hzoo** [comment]
lol nvm? we can land what you have

**Comment by danez** [comment]
Seems we don't add ranges to comments🤔

**Comment by hzoo** [comment]
would be nice to have a perf check for this change (or this vs regular parser)

**Pull request merged**
