### PR TITLE
Fix tests for eslint 3.2

### PR DESCRIPTION
**Pull request by danez**
The added a dot at the end of the no undef message. Now the tests fail either for version 2 or 3 :(

### CODE REVIEW

**Comment by jmeas** [comment]
> Now the tests fail either for version 2 or 3 :(

lol 😓

**Comment by hzoo** [comment]
sigh, we should just drop support for eslint 2 at this point then?

**Comment by jmeas** [comment]
Seems reasonable to me @hzoo.

**Comment by hzoo** [comment]
Since we don't use peerDeps, if we are dropping we should a major for that?

**Comment by jmeas** [comment]
> Since we don't use peerDeps, if we are dropping we should a major for that?

Being conservative about it seems good. I'm :+1: to a major bump.

**Pull request merged**
