### PR TITLE
Add eslint tests - Ref #62

### PR DESCRIPTION
**Pull request by hzoo**
~~Not sure if this is the right way to do this (I think I did the submodule wrong)?~~
Also not sure about using `;` and `cd` in npm scripts and all that.
I did `git submodule add https://github.com/eslint/eslint eslint`

`npm run prepare-eslint-tests && npm run eslint-tests`

@sebmck, @Cellule

Getting 88 errors at the moment.

### CODE REVIEW

**Comment by sebmck** [comment]
`cd` should be fine. `;` on Windows wont be though. Use `command && command` instead.

**Comment by Cellule** [comment]
you could put `npm run prepare-eslint-tests && npm run eslint-tests` in an npm script or directly in script `test` like `mocha && npm run prepare-eslint-tests && npm run eslint-tests` I don't know if we want to run eslint tests everytime.

Also, I am not particularly familiar with git submodules, so I won't comment on it, but it's seems fine. I am only concern about publishing. Will the folder `eslint` be publish along with everything else ?

**Comment by hzoo** [comment]
Ok fixed to use `&&` instead of `;`. Originally I put it in mocha but I figured it would be better to run it separately until we can get the tests to pass?
Also I don't think submodules are included in the publish? Looks like I need to add `git submodule update --init` like in babel which has traceur as a git submodule.

**Comment by hzoo** [comment]
@sebmck So the eslint submodule won't be automatically be there when doing `npm install` since you have to run `git submodule update` right? So this should be good to run. And later we could probably remove the eslint devDependency and just use the submodule?

**Comment by sebmck** [comment]
@hzoo You'll haev to add it to `.npmignore`.

**Comment by hzoo** [comment]
Ah ok added @sebmck

**Comment by hzoo** [comment]
Yeah a lot of errors are due to the tests using `with`.

```text
AssertionError: Should have no errors but had 1: [ { fatal: true,
    severity: 2,
    message: '\'with\' in strict mode',
```4

Also issue with tests involving jsx

```text
 6) comma-spacing <a>,</a>:
     Maximum call stack size exceeded
  ```

I guess we would need to change the parsing options for these tests only (loose mode)?

**Comment by sebmck** [comment]
The `with` ones are alright since Babel is strict mode by default so those are correct. Second one is... weird.

**Comment by hzoo** [comment]
Yeah really weird - seems to be failing at `escope.analyze` https://github.com/eslint/eslint/blob/master/lib/eslint.js#L666-L671

**Pull request merged**
