### PR TITLE
Fix for ESLint@1.9 and npm@3

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes https://github.com/eslint/eslint/issues/4356
This handles a side effect of https://github.com/eslint/eslint/pull/4307

### CODE REVIEW

**Comment by hzoo** [comment]
Will look into it - didn't hear about this issue before.

```
  // monkeypatch estraverse
  estraverse = estraverseRelative.require("estraverse");
  assign(estraverse.VisitorKeys, t.VISITOR_KEYS);

  // monkeypatch estraverse-fb
  var estraverseFb = eslintMod.require("estraverse-fb");
  assign(estraverseFb.VisitorKeys, t.VISITOR_KEYS);

  // ESLint v1.9.0 uses estraverse directly to work around https://github.com/npm/npm/issues/9663
  var estraverseOfEslint = eslintMod.require("estraverse");
  if (estraverseOfEslint !== estraverseFb) {
    assign(estraverseOfEslint.VisitorKeys, t.VISITOR_KEYS);
  }
```

We should probably be able to remove one of these?

And this was added for npm 3 as well https://github.com/babel/babel-eslint/commit/e84741070e68c8c805fef31a53c59849996d7b2e

**Comment by hzoo** [comment]
Will have to test on both npm 2/3 but maybe we can just do

```
  estraverse = eslintMod.require("estraverse");
  assign(estraverse.VisitorKeys, t.VISITOR_KEYS);
```

**Comment by hzoo** [comment]
Goina simply it after this - thanks for looking into it

**Comment by mysticatea** [comment]
> And remove the rest

If do so, npm@3 and eslint@<=1.8 pair might come to not work.

**Comment by hzoo** [comment]
Oh right. I was wondering if we needed the ` eslintMod.require("estraverse-fb");` change at all but I guess that was changed recently so we should keep it?

**Pull request merged**
