### PR TITLE
babylon/espree option alignment

### PR DESCRIPTION
**Pull request by zertosh**
Babylon options: https://github.com/babel/babel/blob/v6.2.2/packages/babylon/src/options.js

cc: @hzoo

### CODE REVIEW

**Comment by hzoo** [comment]
Ah ok thanks - looking at the readme thats the only options now ok. https://github.com/babel/babel/tree/v6.2.2/packages/babylon

Can you add functionSent to the plugins list too?

**Comment by hzoo** [comment]
Never mind i'l do it - thanks!

**Comment by hzoo** [comment]
Made babel-eslint@5.0.0-beta2

**Comment by zertosh** [comment]
Sorry, I stepped away from my computer - but I see you added functionSent - thanks!

**Pull request merged**
