### PR TITLE
fix template type issues

### PR DESCRIPTION
**Pull request by hzoo**
#96

~~WIP. Need to cleanup a lot of stuff.~~

~~Just putting it here for now if anyone wants to test if this PR in it's current form fixes issues.~~
@taion @AlexKVal @kentcdodds

### CODE REVIEW

**Comment by jedrichards** [comment]
This fixed the various errors for me.

For reference they were looking like,

```
/Users/jed/work/autokitty/node_modules/eslint/lib/rules/no-empty-class.js:36
            if (token.type === "RegularExpression" && !regex.test(token.value)
                     ^
TypeError: Cannot read property 'type' of undefined
    at EventEmitter.Literal (/Users/jed/work/autokitty/node_modules/eslint/lib/rules/no-empty-class.js:36:22)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:166:7)
    at Controller.controller.traverse.enter (/Users/jed/work/autokitty/node_modules/eslint/lib/eslint.js:726:25)
    at Controller.__execute (/Users/jed/work/autokitty/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (/Users/jed/work/autokitty/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (/Users/jed/work/autokitty/node_modules/eslint/lib/eslint.js:719:24)
    at processFile (/Users/jed/work/autokitty/node_modules/eslint/lib/cli-engine.js:197:27)
    at /Users/jed/work/autokitty/node_modules/eslint/lib/cli-engine.js:332:26
    at /Users/jed/work/autokitty/node_modules/eslint/lib/util/traverse.js:61:17
```

**Comment by hzoo** [comment]
Ok also fixed code with `Boolean`, `RegularExpression` and the `no-empty-class` issue. Added tests for those.

Ran on `react-bootstrap` (https://github.com/react-bootstrap/react-bootstrap) with no issues (other than finding 3 valid errors for `space-infix-ops`.

**Comment by AlexKVal** [comment]
Confirmed. 
It works now and it is now able to find additional `space-infix-ops` warnings. :+1: 

Thank you :cherries: :sparkle:

**Comment by hzoo** [comment]
Ok awesome. Simplified the code so it's actually somewhat readable and added comments too.

**Comment by hzoo** [comment]
Should we push a new version then @sebmck? Although @kentcdodds hasn't been able to respond yet.

**Comment by kentcdodds** [comment]
I'm sure this would work, but I'll test it now and let you know.

**Comment by kentcdodds** [comment]
Seems to have fixed it for me as well. Thanks!

**Comment by hzoo** [comment]
Ok awesome

**Comment by sebmck** [comment]
> Should we push a new version then @sebmck?

Done. Thanks @hzoo! I can add you to the npm package if you want to push versions. Just need your username.

**Comment by hzoo** [comment]
Ok I made one - `hzoo`.

So I went to https://docs.npmjs.com/getting-started/publishing-npm-packages since I've never made one before. It seems pretty straightforward though? Is it just `npm version <type>; npm publish`? Is the only other thing making a github release?

**Comment by sebmck** [comment]
@hzoo That's basically it. The commands I ran just then to publish a new version were:

 - `npm version patch` - bumps the version in `package.json` and creates a git tag with the new version.
 - `git push --follow-tags` - push the tag and new version added by the previous command to git.
 - `npm publish` - actually publish it.

**Pull request merged**
