### PR TITLE
Create a variable for class properties in scope instead of deleting t…

### PR DESCRIPTION
**Pull request by hzoo**
…he key

Fixes https://github.com/babel/babel-eslint/issues/308

### CODE REVIEW

**Comment by hzoo** [comment]
Lets hope there's no issues 😛

**Comment by vjeux** [comment]
Can you do a release so that I can import it inside of fb codebase? Thanks!

**Comment by hzoo** [comment]
Yep already done all that 😄

**Comment by vjeux** [comment]
you are too fast!

**Comment by hzoo** [comment]
probably got that from @kittens actually

**Pull request merged**
