### PR TITLE
Restore "Fix processing sourceType: script"

### PR DESCRIPTION
**Pull request by josh**
NOT READY TO BE MERGE

-
CC: @hzoo
Reverts babel/babel-eslint#285

### CODE REVIEW

**Comment by josh** [comment]
Need to figure out how to default to `scriptType: "module"` while allowing the option to be overriding by eslint configuration.

**Comment by hzoo** [comment]
So I think we pass the options from parse into monkeypatch and then pass that into the escope part and do `options.sourceType || "module"`

**Comment by josh** [comment]
> So I think we pass the options from parse into monkeypatch and then pass that into the escope part and do options.sourceType || "module"

I don't think that will work. `opts.sourceType` is always set. See it initialized here in eslint  https://github.com/eslint/eslint/blob/2bb8486380a74b076b0fb3244310d0a9edf12d4f/lib/eslint.js#L837

Maybe if we could somehow access `currentConfig.parserOptions.sourceType`?

**Comment by danez** [comment]
I think it should work, as the options that the parser gets are the raw options from eslint (without defaults) + some stuff that eslint needs (loc, range, ...)
I created a PR that should work, can you guys have a look? #288

**Comment by josh** [comment]
Closing this in favor of https://github.com/babel/babel-eslint/pull/288

**Pull request closed without merging**
