### PR TITLE
Clarify what all valid code means in readme

### LINKED ISSUE #555: Babelrc file and readme
In readme you can see this line 

> babel-eslint allows you to lint ALL valid Babel code

How does it relate to `.babelrc` file? Does it mean that it will automatically apply all available syntax plug-ins?

I have a project using `babel-eslint`, and ESLint manages to understand Class Fields event without `.babelrc` file.

```
babel-eslint@7.2.3
eslint@4.12.1
```

### PR DESCRIPTION
**Pull request by the-spyke**
Fixes #555

### CODE REVIEW

**Comment by foiseworth** [comment]
Could we merge this? Lack of this information in the documentation caused me much confusion today

**Comment by kaicataldo** [comment]
Just to note - this won't be true once [this](https://github.com/babel/babel-eslint/pull/711) lands.

**Comment by kaicataldo** [comment]
https://github.com/babel/babel-eslint/pull/711 has landed, making it so that `babel-eslint` will actually read the config file when parsing. I do agree we could clarify what this means, though!

**Comment by the-spyke** [comment]
I couldn't believe that it's still open.

**Comment by the-spyke** [comment]
Sure.

**Pull request closed without merging**
