### PR TITLE
Bump deps for babel 6.26.0

### PR DESCRIPTION
**Pull request by rattrayalex-stripe**
These releases fix bugs we're running into (eg; ESLint crashes when encountering certain Flow features like `...` type spreads). 

I ran `yarn test` locally but did no other testing; let me know if you'd like to see more.

### CODE REVIEW

**Comment by rattrayalex-stripe** [comment]
Judging from comments should fix https://github.com/babel/babel-eslint/issues/443

**Comment by rattrayalex-stripe** [comment]
ping @existentialism LGTY?

**Comment by hzoo** [comment]
@rattrayalex-stripe any issue with just using 8.x?

**Comment by rattrayalex-stripe** [comment]
@hzoo I assume there are backwards-incompatibilities?

**Comment by hzoo** [comment]
there shouldn't, it just updates babel packages, and I guess I should of just made it a patch anyway

**Comment by rattrayalex-stripe** [comment]
I don't know if it's a good idea either 😄 but there are bugs on 7.x that could be fixed, so either that or this should probably be shipped

**Comment by kaicataldo** [comment]
Seems like this should maybe be closed given that the master branch is now on babel@7.

**Comment by rattrayalex-stripe** [comment]
Cool; I think we moved to 8.x anyway. thanks @kaicataldo

**Pull request closed without merging**
