### PR TITLE
Update handling of (Rest/Spread)Element for compatibility with babel@7

### PR DESCRIPTION
**Pull request by lightsofapollo**
Minimal changes to support babel@7 . Some of the underlying behavior has changed (see isRestProperty) and It may make more sense to add backwards compat to babel@7.

### CODE REVIEW

**Comment by zertosh** [comment]
@lightsofapollo, I'll take a look this weekend to see how to make the Babylon 7 transition. I don't think we can just cut over like this. We need to keep to releases for a bit.

**Comment by lightsofapollo** [comment]
@zertosh Thanks! mostly using this to unblock myself as I experiment /w babel@7 alpha/beta.

**Comment by hzoo** [comment]
FYI (if it wasn't clear) it doesn't matter as much if babel-eslint updates to babel 7 yet, because there's nothing that connects this tool to babel itself. It works perfectly fine with babel 6/7 since babel-eslint parses the file separately. It is important to do in the future for sure, when we do release 7 and deprecate v6 so the v6 packages won't be updated anymore

**Comment by hzoo** [comment]
Yeah if someone wants to make the Babel 7 upgrade I'l make an issue

**Pull request closed without merging**
