### PR TITLE
Fix ESLint 6.2.0 + babel-eslint + no-unused-vars false positive with for-in loop

### PR DESCRIPTION
**Pull request by przemyslawzalewski**
In order to reach Espree 6 compatibility, I have manually included the changes by proposed by [golopot](https://github.com/golopot) at https://github.com/babel/babel-eslint/pull/785. This is a candidate for a major release.
I have fixed a single broken test case of a super call being called from regular function and added two test cases - one that validates the `no-unused-vars` works as expected when there is a real issue and another for the false-positive case that caused the breakage.
To make the linting and tests passes on the repo itself, I have removed [self-reference on a broken `babel-eslint` version](https://en.wikipedia.org/wiki/Chicken_or_the_egg) by just extending the [base config](https://github.com/babel/eslint-config-babel) with the current one.
These changes fix the false positives introduced with ESLint 6.2.0 and they occur no more when using the forked version.

Fixes:
https://github.com/babel/babel-eslint/issues/791

### CODE REVIEW

**Comment by karolyi** [comment]
@hzoo @sebmck @danez let's merge this ASAP, shall we.

**Comment by nick** [comment]
The corresponding [issue](https://github.com/eslint/eslint/issues/12117) on eslint has 94 upvotes so seem this issue affects a lot of users. Any chance we can get this merged soon? ☺️

**Comment by tmorehouse** [comment]
Any news on when this can be merged and released?

**Comment by przemyslawzalewski** [comment]
I have proposed [another PR as a PATCH change](https://github.com/babel/babel-eslint/pull/793) that should be easier to integrate and I hope it will be merged soon.
In the meanwhile, I have released a forked package for the ^10 version with the fixes included:

https://www.npmjs.com/package/@przemyslawzalewski/babel-eslint/v/10.0.3

Usage is simple as changing some entires in a package.json:
`"babel-eslint": "^10.0.2"` -> `"@przemyslawzalewski/babel-eslint": "^10.0.3"` and 
`"parser": "babel-eslint"` -> `"parser": "@przemyslawzalewski/babel-eslint"` within the eslint config file.

There is also a fork of the not yet released ^11 branch, however, it may include some breaking changes:
https://www.npmjs.com/package/@przemyslawzalewski/babel-eslint/v/11.0.0

**Comment by hzoo** [comment]
Thanks everyone for the help and @przemyslawzalewski for the PRs! Went ahead and ended up going with @JLHwung's PR https://github.com/babel/babel-eslint/pull/794 which uses ESLint's deps instead of going with peerDeps since it really depends on the version being used and we don't want users to have to install it directly on their own.

Comment here: https://github.com/babel/babel-eslint/issues/791#issuecomment-524664585

**Pull request closed without merging**
