### PR TITLE
Use `lodash` instead of `lodash.pickby`.

### PR DESCRIPTION
**Pull request by wtgtybhertgeghgtwtg**
Since `babel-types` and `babel-traverse` require `lodash`, it's already in the dependency tree.  `lodash.pickby` is not.
So, ironically, using `lodash.pickby` increases the dependencies, instead of decreasing them.

### CODE REVIEW

**Comment by xtuc** [comment]
We could even replace `pickby` with the native filter. Thus removing the dependency.

**Comment by wtgtybhertgeghgtwtg** [comment]
So
```
t.VISITOR_KEYS.filter
```
instead of
```
pick(t.VISITOR_KEYS,
```
I'm ashamed I didn't think of that.

**Comment by xtuc** [comment]
Yes, no worries :+1:. We appreciate your contribution.

Some related PR: babel/babel#5042, babel/babel#5043, babel/babel#5180 and babel/babel#5181

**Comment by wtgtybhertgeghgtwtg** [comment]
Actually, that wouldn't work, since `t.VISITOR_KEYS` is an object used as a map, not an array.

**Comment by xtuc** [comment]
Ok, I was confused by the naming. `pick` should be fine.

**Comment by hzoo** [comment]
Thanks again @wtgtybhertgeghgtwtg!!

**Pull request merged**
