### PR TITLE
Add note that ecmaFeatures are not supported

### PR DESCRIPTION
**Pull request by emmenko**
I thought it would be better to add a note about that. What do you think?

Refs https://github.com/babel/babel-eslint/issues/53

### CODE REVIEW

**Comment by sebmck** [comment]
Don't really think this is necessary and it's evident in both the examples and the copytext of the README that by default you'll be able to write any Babel-compatible code with no config options by default.

**Comment by emmenko** [comment]
I'm sorry but I don't think it was really clear from the README that I can't use all options from `eslint`, at least not from me as you could see. Also, which examples?

**Comment by sebmck** [comment]
> babel-eslint allows you to lint ALL valid Babel code

```json
{
  "parser": "babel-eslint",
  "rules": {
    "strict": 0
  }
}
```

There's no mention of needing specific options to enable certain syntax and this will just confuse more people than it's worth.

**Comment by sebmck** [comment]
People are using `babel-eslint` even though eslint now supports ES6 just because the `ecmaFeatures` option is so confusing.

**Comment by emmenko** [comment]
Ok then I got this wrong from the beginning. Also I just saw in `eslint` documentation this

> Note when using a custom parser, the `ecmaFeatures` configuration property is ignored unless otherwise specified by the parser.

I don't know, something was confusing me all the time. This was the first time using this new stuff and apparently I missed the all point here. 

Sorry for the confusion and thanks for the patient to explain. Hopefully I won't bother you again ;)

**Comment by emmenko** [comment]
@sebmck One more question: when using `eslint` with `babel` (and `babel-eslint` of course), which environment options would you recommend using? I see there is a `es6` option. Is that needed?

Currently I have those `env` variables active

```
"env": {
  "browser": true,
  "jasmine": true,
  "node": true
}
```

**Comment by sebmck** [comment]
The `es6` option would likely include es6 built-ins such as `Promise`, `Map`, `Set` etc.

**Comment by emmenko** [comment]
Ok so would you recommend activating it?

**Comment by sebmck** [comment]
Just add it to your `.eslintrc`?

```json
{
  "env": {
    "es6": true
 }
}
```

**Comment by emmenko** [comment]
Yeah sure, I was more asking if there would be some "complications" with it. I will enable it and see how it goes. Thanks again!

**Pull request closed without merging**
