### PR TITLE
support template strings - Fixes #31

### LINKED ISSUE #31: comma in template string right after ${} causes comma-spacing
minimal example:
```
let a = 1;
console.log(`${a}, b`); // will report comma-spacing
```
comma escaping can be used as a workaround:
```
let a = 1;
console.log(`${a}\, b`); // no error
```

### PR DESCRIPTION
**Pull request by hzoo**
So I tried to understand your comment about the acorn parser here: https://github.com/babel/babel-eslint/pull/93#issuecomment-101463267 and ended up with this?

Got the tests to pass at least!

Not sure what I'm doing haha... so I'm wondering what your thoughts are? 

A fix I didn't do yet is: https://github.com/marijnh/acorn/blob/master/test/tests-harmony.js#L808
where `esprima: "\\n\\r\\b\\v\\t\\f\\\n\\\r\n"` and `acorn: "\n\r\b\u000b\t\f"`

Also looked at
https://github.com/jquery/esprima/pull/1121/files
https://github.com/jquery/esprima/blob/240e0bede7c78ab79927004cef7b422c96ed072e/esprima.js#L1111

### CODE REVIEW

**Comment by hzoo** [comment]
And tell me if you need more tests/comments if you get to this.

**Comment by sebmck** [comment]
Code is a bit crazy but there's probably no way to make it any nicer. Feel free to submit another PR with comments (or I can add you as a collaborator). Thanks for this!

**Comment by hzoo** [comment]
Ok yeah add me i'l go ahead and add comments and probably the rest of the
tests from esprima/acorn

On Thursday, May 14, 2015, Sebastian McKenzie <notifications@github.com>
wrote:

> Code is a bit crazy but there's probably no way to make it any nicer. Feel
> free to submit another PR with comments (or I can add you as a
> collaborator). Thanks for this!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel-eslint/pull/94#issuecomment-102162931>.
>


-- 
Henry Zhu

**Comment by sebmck** [comment]
Woot, thanks @hzoo!

**Pull request merged**
