### PR TITLE
Add failing test for `classPrivateMethods` (regression)

### PR DESCRIPTION
**Pull request by mrtnzlml**
Hi, I read this PR https://github.com/babel/babel-eslint/pull/729 and this issue https://github.com/babel/babel-eslint/issues/728 and it seems like `classPrivateMethods` should work. However, it doesn't. So I added a failing test since I don't know how to fix it.

Thank you very much for checking it.

### CODE REVIEW

**Comment by anthonator** [comment]
Is there a workaround for this until this is fixed?

**Comment by justintime4tea** [comment]
lib/parse.js does not have "classPrivateMethods" listed in the plugins array. It appears that babel-eslint doesn't give a hoot about what you pass it for options either so you can't pass it "classPrivateMethods" to enable it yourself.

The workaround for me (not really practical but makes my editor happy) is to re-add "classPrivateMethods" back into the file... for every project I'm in that it bugs me lol

node_modules/babel-eslint/lib/parse.js
Right around line 21 is an array Plugins
Add it to that.

**Comment by omerdn1** [comment]
This issue is fixed in #801.
Hoping this gets merged soon.

**Comment by kaicataldo** [comment]
Thank you for the PR. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).

**Pull request closed without merging**
