### PR TITLE
Patch SpreadProperty to escope's PatternVisitor

### PR DESCRIPTION
**Pull request by Constellation**
Once new escope is released, we can patch SpreadProperty to PatternVisitor.
This will solve estools/escope#88 and eslint/eslint#4481.

See escope side PR: https://github.com/estools/escope/pull/89

### CODE REVIEW

**Comment by mAiNiNfEcTiOn** [comment]
Well, I have been testing this code (using the branch directly, because this is a serious issue), and so far seems to be ok...

Any perspectives of when will it be merged?

**Comment by samwhite0** [comment]
+1: This seems to fix #210 - using the code locally right now to fix the `no-redeclare` problem

**Comment by hzoo** [comment]
Ok merging and releasing

**Comment by hzoo** [comment]
@Constellation getting errors after merging now - don't have time at the moment to look into it

**Comment by evocateur** [comment]
The pull request was using eslint 1.9.0, and the merged test used eslint 1.10.1. Something changed between 1.9.0 and 1.10.1 was evidently not backward-compatible.

**Pull request merged**
