### PR TITLE
add plugin classPrivateMethods

### PR DESCRIPTION
**Pull request by zhernosekim**
This commit resolves error "Parsing error: This experimental syntax requires enabling the parser plugin: 'classPrivateMethods' "

### CODE REVIEW

**Comment by axten** [comment]
@hzoo please merge this into 10.x branch and release it.
we are currently still unable to use private class methods in our projects because of babel-eslint

**Comment by stevelacey** [comment]
Spent a lot of time trying to work out how to set this before realising it's out of reach. LGTM 🙌

**Comment by tirithen** [comment]
What is the progress on this pull request? I would be nice not having to use this pull request as an npm dependency. Is anything missing or solved in a bad way? Looks like such a small change.

**Comment by kaicataldo** [comment]
As noted [here](https://github.com/babel/babel-eslint#note-babel-eslint-is-being-moved-into-the-babel-monorepo-please-follow-along-here-to-track-our-progress), we're currently in the process of moving this project into the the `babel/babel` monorepo. The latest prerelease version of `babel-eslint@11` now reads your Babel config and enables the necessary parser plugins for your project.

**Comment by kaicataldo** [comment]
Thank you for the PR. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).

**Pull request closed without merging**
