### PR TITLE
update to babel6

### PR DESCRIPTION
**Pull request by hzoo**
related PR https://github.com/babel/acorn-to-esprima/pull/3

@sebmck 

- specific babel packages
- remove references to comprehensions
- update acorn-to-esprima
- update babylon options

Need to add more test cases/repos to test

### CODE REVIEW

**Comment by lyonlai** [comment]
any update on this?

**Comment by olalonde** [comment]
Bump... had to disable eslint after switching to babel 6.

**Comment by reggi** [comment]
What's the word on this?

**Comment by evocateur** [comment]
there are still a few issues I've discovered, deep in the nasty bowels of babylon as far as I can tell. will report back after my spelunking is finished.

**Comment by hzoo** [comment]
There is definetely an issue with the loc/range for objectproperty/objectmethod changes

**Comment by evocateur** [comment]
I've been hitting issues with `StringLiteral` nodes losing their `extra` property (and thus their derived `raw` property, which eslint uses in various checks, like `jsx-quotes`). A `StringLiteral` node's `extra` property is being [set to `null` in babylon](https://github.com/babel/babel/blob/master/packages/babylon/src/plugins/jsx/index.js#L249), and I don't understand why the original metadata isn't allowed through.

**Comment by hzoo** [comment]
- [ ] ClassMethod fails
```js
class A {
  constructor(a) {

  }
}
```

**Comment by hzoo** [comment]
Going to do a prerelease

**Pull request merged**
